config/routes.rb
ClosetCrunch::Application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :sessions, only: [:new, :create, :destroy]
  resources :pages, only: :show
  resources :password_resets
  resources :users, except: :index do
    member do
      get :activate
    end
  end

  get '/join' => 'users#new', as: :new_user_registration
  get '/login' => 'sessions#new', as: :new_user_session
  post '/login' => 'sessions#create', as: :create_user_session
  get '/logout' => 'sessions#destroy', as: :get_destroy_user_session
  delete '/logout' => 'sessions#destroy', as: :destroy_user_session

  get 'oauth/callback' => 'oauths#callback'
  get 'oauth/:provider' => 'oauths#oauth', as: :auth_at_provider

  get '/:id' => 'pages#show'

  root to: 'pages#show', id: :home
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/area.rb
class Area < ActiveRecord::Base
  attr_accessible :name
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid
  belongs_to :user
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :description, :keywords, :published, :slug, :title

  scope :published, -> { where published: true }

  validates :title, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true
  validates :content, presence: true

  def to_param
    slug
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  attr_accessible :username, :email, :password, :salt, :crypted_password, :agree, :authentications_attributes

  has_many :authentications, dependent: :destroy

  accepts_nested_attributes_for :authentications

  scope :recent, -> { order 'id desc' }
  scope :most_active, -> { order 'sign_in_count desc' }

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true
  validates :agree, acceptance: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  ActionView::Base.field_error_proc = Proc.new do |html, instance|
    if html =~ /label/
      if html =~ /agreement_to_terms/
        %(<div class="error">#{html}<p class="help-block">#{instance.error_message.first}</p></div>).html_safe
      else
        %(<div class="error">#{html}</div>).html_safe
      end
    else
      if html =~ /user_agree/
        %(<div class="error">#{html}</div>).html_safe
      else
        %(<div class="error">#{html}<p class="help-block">#{instance.error_message.first}</p></div>).html_safe
      end
    end
  end
end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
  skip_before_filter :require_login

  def oauth
    login_at params[:provider]
  end

  def callback
    provider = params[:provider]

    if @user = login_from(provider)
      redirect_to root_path, flash: { success: "Logged in from #{provider.titleize}" }
    else
      begin
        @user = create_from provider
        @user.activate!
        reset_session
        auto_login @user
        redirect_to root_path, flash: { success: "Logged in from #{provider.titleize}" }
      rescue
        redirect_to root_path, flash: { success: "Failed to login from #{provider.titleize}" }
      end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :page_not_found

  def show
    @page = Page.published.find_by_slug!(params[:id])
  end

  protected

  def page_not_found
    raise ActionController::RoutingError.new('Page Not Found')
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :require_login

  def new
  end

  def create
    @user = User.find_by_email params[:email]
    @user.deliver_reset_password_instructions! if @user
    redirect_to root_path, flash: { notice: 'Reset instructions have been sent to your email' }
  end

  def edit
    @user = User.load_from_reset_password_token params[:id]
    @token = params[:id]
    not_authenticated unless @user
  end

  def update
    @token = params[:token]
    @user = User.load_from_reset_password_token params[:token]
    not_authenticated unless @user

    if @user.change_password!(params[:user][:password])
      redirect_to root_path, flash: { notice: 'Your password was updated successfully' }
    else
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password], params[:remember_me])
      User.increment_counter(:sign_in_count, @user)
      redirect_back_or_to root_path, success: 'Successfully logged in'
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, flash: { success: 'Successfully logged out' }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]
    if @user.save
      login(params[:user][:email], params[:user][:password])
      redirect_to root_path, flash: { success: 'Thank for joining Closetcrunch!' }
    else
      render :new
    end
  end

  def edit
    @user = load_user
  end

  def update
    @user = load_user
    if @user.update_attributes params[:user]
      redirect_to root_path, flash: { success: 'Your profile has been saved' }
    else
      render :edit
    end
  end

  def destroy
    user = load_user
    user.delete
    redirect_to root_path, flash: { success: 'Your account has been disabled' }
  end

  def activate
    if @user = User.load_from_activation_token(params[:id])
      @user.activate!
      redirect_to root_path, flash: { success: 'You\'ve successfully activated your account' }
    else
      not_authenticated
    end
  end

  protected

  def load_user
    User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
<!--[if IE 7 ]><html class="ie ie7" lang="en"><![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html class="" lang="en"><!--<![endif]-->
%head
  / meta
  %meta{ charset: 'utf-8' }
  %meta{ name: 'keywords', content: '' }
  %meta{ name: 'description', content: '' }
  %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1' }
  = csrf_meta_tags

  / css
  = stylesheet_link_tag '//fonts.googleapis.com/css?family=Carrois+Gothic'
  = stylesheet_link_tag 'application', media: :all
  / [if IE 7]
    = stylesheet_link_tag 'font-awesome-ie7.min'

  / js
  = javascript_include_tag 'application'

  %title ClosetCrunch
%body{ style: 'margin-top: 0px' }
  #wrapper.container-fluid
    = render 'layouts/shared/alerts'

    .ie-dropdown-fix
      = render 'layouts/shared/header'
      = render 'layouts/shared/nav'

    = render 'layouts/shared/breadcrumbs'

    .row-fluid.contentmargin
      = yield
      .span2.adright
        .row-fluid= image_tag asset_path('ads/SNP_2922332_en_v0.jpg'), size: '200x200'
        %br
        .row-fluid= image_tag asset_path('ads/text-ad.jpg'), size: '159x600'

  = render 'layouts/shared/footer'

app/views/layouts/email.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Closetcrunch.com</title>
    <style type="text/css">
      body {
        background-color: #F0F0F0;
      }
    </style>
  </head>
<body>
  <table width="700" border="0" align="center" style="border:5px solid #FFFFFF; background-color:#FFFFFF; margin-top:25px; font-family: 'Helvetica Neue', Helvetica, Tahoma, Arial, sans-serif !important; color:#495678;">
    <tr>
      <td style="padding: 5px 0;">
        <a href="http://www.closetcrunch.com">
          <img src="http://closetcrunch.dev<%= asset_path('email-logo.jpg') %>" width="155" height="80" alt="" style="border:none;" />
        </a>
      </td>
    </tr>
    <tr>
      <td style="font-size: 13px; padding:5px 15px; line-height:160%;">
        <%= yield %>
      </td>
    </tr>

    <tr>
      <td style="padding:5px 15px; font:11px/150% Verdana, Geneva, sans-serif; text-align:center; background-color:#495678; color:#FFFFFF; ">
        <span style="font-size:12px; padding:10px 15px; line-height:160%;">
          This message was sent to <a href="#" style="text-decoration:none; color:#ffffff;"><%= @user.email %></a> from <a href="#" style="text-decoration:none; color:#ffffff;">Closetcrunch.com</a>.
        </span>
      </td>
    </tr>
  </table>
</body>
</html>

app/views/layouts/shared/_alerts.html.haml
- flash.each do |name,msg|
  .alert{ id: name }
    %button.close{ data: { dismiss: 'alert' }, type: 'button' } &times;
    = msg

app/views/layouts/shared/_breadcrumbs.html.haml
.row-fluid
  .span10
    %ul.breadcrumb
      %li
        = link_to 'Home'
        %span.divider >>
      %li.active Men
  .span2.textright

app/views/layouts/shared/_footer.html.haml
.footer
  .container-fluid
    .row-fluid.footerdescription
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fermentum tortor
      ut nisl vehicula gravida. Nulla hendrerit elit vel risus pellentesque rutrum.
      Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia
      Curae; Sed sit amet lectus quis nisl laoreet sodales. Praesent imperdiet ipsum
      quis nulla adipiscing in accumsan risus consectetur. Nunc ultricies dictum lorem,
      non fringilla nulla suscipit vitae. In hac habitasse platea dictumst. Vivamus
      vel arcu ac diam aliquam tincidunt et ac sem. Aenean at lacinia mi. Fusce laoreet,
      mi egestas elementum cursus, magna justo hendrerit augue, at vehicula tortor
      eros a ligula.
    .row-fluid.footernav
      %ul.footernavlist
        %li= link_to 'Home', '#'
        %li= link_to 'About Us', '#'
        %li= link_to 'FAQ\'s', '#'
        %li= link_to 'User Agreement', '#'
        %li= link_to 'Privacy Policy', '#'
        %li= link_to 'Contact Us', '#'
    .row-fluid
      Logged in as
      = link_to 'example@example.com', '#'
      = raw "(#{link_to 'Log out', '#'})"
    %br
    .row-fluid
      .span9
        Copyright &copy; 2013 Closetcrunch.com. All Rights Reserved
      .span3.textright
        %ul.socialfooter
          %li
            = link_to '#' do
              %i.icon-facebook
            = link_to '#' do
              %i.icon-twitter

app/views/layouts/shared/_header.html.haml
.row-fluid.logomargin
  .span2
    = link_to image_tag(asset_path('logo.jpg'), size: '199x67', alt: 'Closetcrunch Logo'), root_path
  .span3
    .row-fluid.areaname Los Angeles, CA
    .row-fluid= link_to '(Change your area)', '#'
  .span4.offset3.textright#regform
    .row-fluid
      .input-append
        %input.span10.bigformoneline.searchmargintop#appendedInputButton{ placeholder: 'Search...', type: 'text' }
        %button.btn.searchbutton{ type: 'button' }
          %i.icon-search
    .row-fluid
      - if current_user
        Logged in as
        = link_to current_user.username, '#'
        = raw "(#{link_to 'Log out', destroy_user_session_path, method: :delete})"
      - else
        = link_to 'Log in', new_user_session_path

app/views/layouts/shared/_nav.html.haml
#navigation
  %ul#nav
    %li= link_to 'Home', '#'
    %li= link_to 'Men', '#'
    %li
      = link_to 'Women', '#'
      %ul
        %li= link_to 'Petite', '#'
        %li= link_to 'Tall', '#'
        %li= link_to 'Plus Size', '#'
        %li= link_to 'Maternity', '#'
    %li
      = link_to 'Children', '#'
      %ul
        %li= link_to 'Infant Boy', '#'
        %li= link_to 'Infant Girl', '#'
        %li= link_to 'Toddler Boy', '#'
        %li= link_to 'Toddler Girl', '#'
        %li= link_to 'Boy', '#'
        %li= link_to 'Girl', '#'
    %li= link_to 'Forums', '#'
    %li
      = link_to 'More', '#'
      %ul
        %li= link_to 'About Us', '#'
        %li= link_to 'Privacy Policy', '#'
        %li= link_to 'Terms of Service', '#'
        %li= link_to 'Contact Us', '#'
    - if current_user
      %li
        = link_to 'My Account', '#'
        %ul
          %li= link_to 'New Listing', '#'
          %li= link_to 'My Listings', '#'
          %li= link_to 'Watchlist', '#'
          %li= link_to 'Account Settings', '#'
          %li= link_to 'Logout', '#'
      %li.membernav
        = link_to '#' do
          %i.icon-plus
          New Listing
.nav-shadow
.clear

app/views/oauths/callback.html.haml
%h1 Oauths#callback
%p Find me in app/views/oauths/callback.html.haml

app/views/oauths/oauth.html.haml
%h1 Oauths#oauth
%p Find me in app/views/oauths/oauth.html.haml

app/views/pages/show.html.haml
.span10.borderright
  %h3= @page.title
  = @page.content

app/views/password_resets/create.html.haml
%h1 PasswordResets#create
%p Find me in app/views/password_resets/create.html.haml

app/views/password_resets/edit.html.haml
.span10.borderright
  %h2 Choose a new password
  .row-fluid This is text that I can control from the the admin section.
  %br
  #regform
    = form_for @user, url: password_reset_path(@user), html: { method: :put } do |f|
      .row-fluid
        %strong
          = @user.email
      %br
      .row-fluid= f.password_field :password, class: 'bigformoneline span9', placeholder: 'New Password'
      = hidden_field_tag :token, @token
      %hr
      .row-fluid
        .span4
          %button.btn.btn-large.btn-block.btn-main{ type: 'submit' } Change Password

app/views/password_resets/new.html.haml
.span10.borderright
  %h2 Reset password
  .row-fluid This is text that I can control from the the admin section.
  %br

  #regform
    = form_tag password_resets_path, method: :post do
      .row-fluid= email_field_tag :email, nil, class: 'bigformoneline span9', placeholder: 'Email Address'
      %hr
      .row-fluid
        .span4
          %button.btn.btn-large.btn-block.btn-main{type: 'submit'} Reset Password

app/views/password_resets/update.html.haml
%h1 PasswordResets#update
%p Find me in app/views/password_resets/update.html.haml

app/views/users/edit.html.haml
%h1 Users#edit
%p Find me in app/views/users/edit.html.haml

app/views/users/new.html.haml
.span7.borderright
  %h2 Join Closetcrunch.com
  .row-fluid You control this from the admin section
  %br
  .recwell#regform
    = form_for @user do |f|
      .row-fluid
        = text_field_tag :full_name, nil, class: 'bigformoneline span9', placeholder: 'Full Name'
      .row-fluid
        = f.text_field :username, class: 'bigformoneline span9', placeholder: 'Username'
      .row-fluid
        = f.email_field :email, class: 'bigformoneline span9', placeholder: 'Email Address'
      .row-fluid
        = f.password_field :password, class: 'bigformoneline span9', placeholder: 'Password'
      .row-fluid
        = f.check_box :agree
        = f.label :agree,
          raw("I agree to the terms of the #{link_to 'User Agreement', '#'} and #{link_to 'Privacy Policy', '#'}"),
          class: 'checkbox agreement_to_terms'
      %hr
      .row-fluid
        .span3
          %button.btn.btn-large.btn-block.btn-orange{ type: 'submit' } Join

.span3.borderright
  %h4 Join via
  .row-fluid
    = link_to auth_at_provider_path(provider: :facebook), class: 'btn btn-large btn-block btn-facebook' do
      %i.icon-facebook
      Facebook
  %br
  .row-fluid
    = link_to auth_at_provider_path(provider: :twitter), class: 'btn btn-large btn-block btn-twitter' do
      %i.icon-twitter
      Twitter
  %hr
  %h4 Already a member?
  .row-fluid
    = link_to 'Sign in', '#', class: 'btn btn-large btn-block btn-main'

app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/users/show.html.haml